services:
  web-server:
    image: nginx:latest
    container_name: mi-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
      - web_data:/usr/share/nginx/html
    depends_on:
      - sftp-server

  sftp-server:
    image: atmoz/sftp
    container_name: mi-sftp
    ports:
      - "2222:22"
    command: usuario:contrasenia:1001:1001:upload
    volumes:
      - web_data:/home/usuario/upload

volumes:
  web_data: